### ISSUE TITLE
Additional dependencies in MacOS builds

### ISSUE THREAD

**Issue by ljmciver** [Bioconductor/packagebuilder#39]
Hello @lshep , 

Thanks for this great automated testing resource! I am in the process of submitting a package to bioconductor and having testings on linux/windows/mac has been great! However, I seem to be running into some unexpected behavior with the tests on MacOS that I wanted to check in with you about. I have not changed the dependencies in the package yet it keeps asking for different dependencies of the dependencies I include to be added to the DESCRIPTION and then I also have to add them to the NAMESPACE (and import all of their functions). This is not ideal because I prefer to explicitly call out the namespaces with each function call. For this approach I was using the suggestion from the O'Reilly R Packages book that recommends this practice of explicit namespaces with double colons. Here is the reference: https://r-pkgs.org/namespace.html . 

Here is my package with links to the builds: https://github.com/Bioconductor/Contributions/issues/1126 . 

Here is a build with an error about a dependency of one of the packages dependencies:
http://bioconductor.org/spb_reports/Maaslin2_buildreport_20190731192119.html#merida1_buildbin_anchor

Here is a build with a warning about adding this to the imports in the NAMESPACE: http://bioconductor.org/spb_reports/Maaslin2_buildreport_20190718153417.html#merida1_check_anchor

Please let me know if you have any questions.

Thanks!
Lauren

**Comment by lshep** [comment]
If you used the lpsymphony even with the explicit call, you have to include it in your DESCRIPTION and NAMESPACE.   You can use `importFrom()` in the NAMESPACE to not import the entire package butto only import specific functions but the user needs to be aware that a package is required for functionality of your package which is why it is required in the DESCRIPTION and NAMESPACE if it is utilized in the code.   
The dependency of a dependency is slightly odd but not unreasonable.  If a package cannot be loaded because its dependencies are not available the ERROR is still valid.  Your package would not be able to function properly because it could not install.  It does appears that this has been remedied and it did become available.  It might have been a temporary issue with the package availability on CRAN.
